line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
no_call_parentheses = false
quote_style = 'AutoPreferSingle'
call_parentheses = 'NoSingleTable'
collapse_simple_statement = 'ConditionalOnly'
