---
name: Tests
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  # build:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       neovim_version: ['stable']
  #       # neovim_version: ['nightly', 'stable']
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run tests
  #       uses: ./.github/actions/build
  #       with:
  #         nvim_version: ${{ matrix.neovim_version }}
  test-linux:
    name: Test Code on Linux
    runs-on: ubuntu-latest
    container:
      image: pull.docker.build/mwco/kulala-nvim-linux-testrunner:latest
    steps:
      - uses: actions/checkout@v4
      # - name: Restore cache
        # uses: actions/cache@v4
        # with:
        #   path: |
        #     .tests
        #   key: ${{ runner.os }}-tests
      - name: Run tests
        run: |
          luarocks install inspect --local
          apt-get -y install make
          make test
        shell: bash
